### ISSUE TITLE
1.16版本go依旧无法运行

### ISSUE THREAD

**Issue by CY-Christin** [SealinGp/cisasntyi#1]
你好，我是在v2上提问的网友。  
我已经改装了1.16版的go `go version go1.16 linux/amd64`但是还是无法运行。
运行报错
```
cisasntyi git:main # bash dev.sh                                  ✹
# runtime
/usr/local/go/src/runtime/mgcsweepbuf.go:87:80: memstats.gc_sys undefined (type mstats has no field or method gc_sys)
/usr/local/go/src/runtime/mgcsweepbuf.go:106:102: memstats.gc_sys undefined (type mstats has no field or method gc_sys)
dev.sh: line 4: ./cisasntyi: No such file or directory
```
我在网上搜索也没有搜到相关问题，希望得到帮助。

**Comment by SealinGp** [comment]
稍等，我发个包，你直接用吧

**Comment by SealinGp** [comment]
适用于Ubuntu版本的cisasntyi二进制文件
http://owncloud.sea8.top/index.php/s/WCHm4rjUnGZd17x
下载完丢进去
```bash
mv app.yml app_dev.yml && bash dev.sh 
```

**Comment by SealinGp** [comment]
另外，你这个报错在https://github.com/golang/go/issues/43320 中有提到，你可以看看，应该是安装时go的问题

**Comment by CY-Christin** [comment]
你发给我那个文件执行提示`./cisasntyi: Permission denied`  
但是我安装你发给我那个删除重装就可以自己运行了。运行后日志里只有`2021/09/25 10:39:17 [I] pid:3544125`，是正常现象吗？

**Comment by SealinGp** [comment]
正常,有货的话,大概效果是这样
![微信图片_20210925184621](https://user-images.githubusercontent.com/32982627/134768724-dad16b7a-86db-46ae-9ae9-005c59f6b6d6.jpg)

但是你需要修改配置文件里面你关心的机型

**Comment by CY-Christin** [comment]
> 正常,有货的话,大概效果是这样
> ![微信图片_20210925184621](https://user-images.githubusercontent.com/32982627/134768724-dad16b7a-86db-46ae-9ae9-005c59f6b6d6.jpg)
> 
> 但是你需要修改配置文件里面你关心的机型

好的 已经修改了。非常感谢。
