### ISSUE TITLE
IPV6的VPS用不了

### ISSUE THREAD

**Issue by TrayBer** [SealinGp/cisasntyi#2]
配置好之后，始终收不到通知提醒，是否本身不支持IPV6 ONLY VPS？

**Comment by SealinGp** [comment]
这个应该跟ipv6没关系,没有监听任何端口,只要你的vps出口网络没问题,那么应该可以,建议
1.ping一下你的配置文件里面的bark domain看是否通
2.pull一下最新commit,然后看日志, 后面有新增库存日志打印出来
